site_name: TTMolE Documentation
site_url: https://jerschro.github.io/ttmole_documentation/
site_author: Jeremy Schroeder
site_description: Documentation for python-based program for editing and creating molecular structures.
repo_name: jerschro/ttmole_documentation
repo_url: https://github.com/jerschro/ttmole_documentation

nav:
  - Home : index.md
  - Introduction : intro.md
  - Installation : installation.md
  - Guides : guides/index.md
  - Bugs & Suggestions: bugs_suggestions.md
  - Sitemap : sitemap.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigate.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: lime
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference


plugins:
  - search
  # - mkdocstrings
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true

markdown_extensions:
  - tables
  - attr_list
  - md_in_html


extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:jeremynschroeder@gmail.com
    - icon: fontawesome/solid/t
      link: https://www.depts.ttu.edu/me/combustionlab/

copyright: |
  &copy; 2024 Jeremy Schroeder